### ISSUE TITLE
where to put mappings/crosswalks

### ISSUE THREAD

**Issue by debpaul** [tdwg/ncd#12]
@stanblum I was planning to create a directory and put these types of documents (crosswalks) in it. We have more crosswalks to add. For discoverability, do you think it's better to put (link) them in the relevant section of the draft task charter? OR, put them on a wiki here in GitHub and link to the wiki?

(regarding conversation in (closed) ticket https://github.com/tdwg/ncd/issues/11)

**Comment by debpaul** [comment]
I've added a folder for crosswalks and related documents. 
https://github.com/tdwg/ncd/tree/master/crosswalks-related-docs

Is it okay to put use case docs in there too? Or do we need / want a separate directory?

**Comment by debpaul** [comment]
I've created a wiki page where we can organize, document and refer to current Use Cases and Crosswalk work for NCD. https://github.com/tdwg/ncd/wiki/Crosswalks-and-Use-Cases

**Comment by stanblum** [comment]
I think the wiki is a good place to put many of those things, and then link and highlight the wiki from the NCD landing page.  Unfortunately for crosswalks, I think they need to be in a spreadsheet format.  I don't know of any better tool. And tables in markdown and HTML are just too much work to maintain.  I'd much rather do that in a simple spreadsheet.  And given the Microsoft Excel isn't as good for collaboration, I think we should put the crosswalks in GoogleSheets.  So that begs the question, do you want to set up a workspace (folder or folder hierarchy) in Google Drive for NCD stuff?  I put the NCD-EAD crosswalk in a google sheet; can drop that into any folder you want to share here.  We can dump other versions of that spreadsheet and put another format of the crosswalks into this repo.  Or we can ask around for a better solution for supporting crosswalk collaboration.  ?

**Comment by debpaul** [comment]
Hi @stanblum At least one of the crosswalk docs is in Excel - so possible to copy it to a google sheet. Another is a word doc. It will not be trivial to move that to google sheets. 

Do we need these resources to be in google sheets before the task group charter can be reviewed?

**Comment by connierinaldo** [comment]
I can try working on the word doc. I can keep looking for an excel version but I did not find it on my previous pass.

Sent from my iPhone

On Feb 19, 2018, at 1:27 PM, Debbie Paul <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @stanblum<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_stanblum&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=j1Xr4DSH9BbW6JjvkKmN95MaY2B7j1HqlmHGfHESi9k&m=SqbzJDREPz0tullgOGreDvuebubbEMRlMVOzEETn0zw&s=KEQXpAjTf1JixDqi4zC6DRvkhj4PH6SnKofac7015Uo&e=> At least one of the crosswalk docs is in Excel - so possible to copy it to a google sheet. Another is a word doc. It will not be trivial to move that to google sheets.

Do we need these resources to be in google sheets before the task group charter can be reviewed?

**Comment by debpaul** [comment]
Thanks! @connierinaldo Note we're working on putting all the docs in one spot. We'll be putting mappings into google spreadsheets (@stanblum is making a folder for us - today perhaps). Original documents are in folder here in the repo: https://github.com/tdwg/ncd/tree/master/crosswalks-related-docs and there's a wiki in progress for where to put use cases and links to the crosswalk work, see https://github.com/tdwg/ncd/wiki/Crosswalks-and-Use-Cases

**Comment by stanblum** [comment]
I could not find a better tool for maintaining a simple crosswalk, so I created an NCD folder in Google Drive, and uploaded the NCD_EAD crosswalk there.  Also, posted the GRBio crosswalk across the major bio-repository registries.  Initial files (xls) have been posted to the GitHub repo, but I think most will find it much easier to use the Google sheets for review, comment, and edits.  I think I've added links in the readme.md files to the NCD Wiki (GitHub) and added links in the wiki to the crosswalks and use-cases.
